# Version 0.0

## Add R CMD check button to the github repository
```{r}
#--- R CMD check ---#
usethis::use_github_action_check_standard()
```

## Packages to use

```{r}
usethis::use_package("data.table")
usethis::use_import_from("dplyr", "mutate")
usethis::use_import_from("dplyr", "select")
usethis::use_import_from("dplyr", "filter")
usethis::use_import_from("dplyr", "left_join")
usethis::use_import_from("dplyr", "rowwise")
usethis::use_import_from("dplyr", "case_when")
usethis::use_import_from("dplyr", "ungroup")
usethis::use_import_from("dplyr", "relocate")
usethis::use_import_from("dplyr", "nest_by")
usethis::use_import_from("dplyr", "pull")
usethis::use_import_from("dplyr", "rename")
usethis::use_import_from("dplyr", "slice")
usethis::use_import_from("dplyr", "arrange")
usethis::use_import_from("dplyr", "glimpse")
usethis::use_package("ggplot2")
usethis::use_package("magrittr")
usethis::use_package("leaflet")
usethis::use_package("sf")
usethis::use_package("lwgeom")
usethis::use_package("purrr")
usethis::use_package("terra")
usethis::use_package("tibble")
usethis::use_package("tidyr")
usethis::use_package("ggpubr")
usethis::use_package("ggExtra")
usethis::use_package("zip")
usethis::use_package("bookdown")
# usethis::use_package("RColorBrewer")
usethis::use_package("measurements")
# usethis::use_package("knitr")
usethis::use_package("rmarkdown")
usethis::use_package("tmap")
usethis::use_pipe() # can use %>% after this
```

## Folders, files to ignore

```{r}
usethis::use_build_ignore(c("dev_notes.md", "checklist.md", "notes.md", "organize.R", "structure.rmd", "todo.md", "test.R", "docs", "README.html", "debug", "random-vs-orthogonal.Rmd", "test", "dev", "_pkgdown.yml", "R_retired"))
```

## Create a folder where codes to generate datasets are created

```{r}
usethis::use_data_raw("generate_data.R")
```

## Vignette

```{r}
usethis::use_vignette("basic-work-flow")
```

## Article

```{r}
usethis::use_article("V0-basic-work-flow")
usethis::use_article("V1-trial-design-options")
usethis::use_article("V2-ab-line")
usethis::use_article("V3-change-rates-manually")
usethis::use_article("V4-diagnose-td")
usethis::use_article("V5-understanding-structure")
usethis::use_article("V6-non-regular-field")
usethis::use_article("V7-visualize-from-scratch")
```

## Other documents

```{r}
usethis::use_readme_rmd()
usethis::use_news_md()
```

```{r}
devtools::check()
usethis::use_cran_comments()
```

## Package documents

```{r}
#--- document the functions ---#
devtools::document()
```

## Build vignette website 

```{r}
rmarkdown::render("/Users/tmieno2/Dropbox/DIFM_Brain/ofpetrial/vignettes/articles/index.Rmd")
pkgdown::build_site()
```

## Check Atlas build

```{r}
rhub::rhub_check()
```

## Submission to CRAN

```{r}
devtools::submit_cran()
```

# Version 0.1.1

```{r}
devtools::document()
rhub::rhub_check()
```

```{r}
usethis::use_version("patch")
devtools::submit_cran()
```